### ISSUE TITLE
Uploading tagged versions to PyPi

### ISSUE THREAD

**Issue by ayalash** [vmalloc/pyforge#25]
https://github.com/vmalloc/pyforge/pull/24 Move CI from Travis CI to GitHub actions.
the PR run tests but doesn't adds automatic deployment for tags.

I found this actions for uploading python packages (written by Pypa organization):
https://github.com/marketplace/actions/pypi-publish

I never use this action - @vmalloc Do we want to add it to this repository?

**Comment by vmalloc** [comment]
I used to do it with twine... I don't know that specific action... I'm fine with trying it out though
